import { loadLanguages } from 'reprism';
// import arduino from 'reprism/languages/arduino';
import bash from 'reprism/languages/bash';
import basic from 'reprism/languages/basic';
import c from 'reprism/languages/c';
import csharp from 'reprism/languages/csharp';
import cpp from 'reprism/languages/cpp';
import clojure from 'reprism/languages/clojure';
import coffeescript from 'reprism/languages/coffeescript';
import dart from 'reprism/languages/dart';
import django from 'reprism/languages/django';
import docker from 'reprism/languages/docker';
// import ejs from 'reprism/languages/ejs';
// import elm from 'reprism/languages/elm';
import git from 'reprism/languages/git';
import go from 'reprism/languages/go';
import graphql from 'reprism/languages/graphql';
import haml from 'reprism/languages/haml';
// import handlebars from 'reprism/languages/handlebars';
import haskell from 'reprism/languages/haskell';
import java from 'reprism/languages/java';
import json from 'reprism/languages/json';
import kotlin from 'reprism/languages/kotlin';
import less from 'reprism/languages/less';
import lisp from 'reprism/languages/lisp';
import lua from 'reprism/languages/lua';
import markdown from 'reprism/languages/markdown';
import nginx from 'reprism/languages/nginx';
import pascal from 'reprism/languages/pascal';
import perl from 'reprism/languages/perl';
// import php from 'reprism/languages/php';
import pug from 'reprism/languages/pug';
import python from 'reprism/languages/python';
import r from 'reprism/languages/r';
import jsx from 'reprism/languages/jsx';
// import regex from 'reprism/languages/regex';
import ruby from 'reprism/languages/ruby';
import rust from 'reprism/languages/rust';
import sass from 'reprism/languages/sass';
import scss from 'reprism/languages/scss';
// import sql from 'reprism/languages/sql';
import swift from 'reprism/languages/swift';
import typescript from 'reprism/languages/typescript';
import vim from 'reprism/languages/vim';
import vb from 'reprism/languages/visual-basic';
import wasm from 'reprism/languages/wasm';
import yaml from 'reprism/languages/yaml';

const languages = [bash, basic, c, csharp, cpp, coffeescript, clojure, dart, django, docker, git, go, graphql, haml, haskell, java, json, kotlin, less, lisp, lua, markdown, nginx, pascal, perl, pug, python, r, jsx, ruby, rust, sass, scss, swift, typescript, vim, vb, wasm, yaml];

const LanguageSupport = loadLanguages(languages);

export default LanguageSupport;
